### ISSUE TITLE
Hello, how you generate defenitions?

### ISSUE THREAD

**Issue by AmsTaFFix** [brian428/ext-typescript-generator#3]
Now, i try to make ExtJS Application with TypeScript. And i want to have up-to-date ExtJS definitions, can you explain how to work with your generator? 

(Sorry for my English)

**Comment by brian428** [comment]
I generate JSON docs using JSDuck, such as:

jsduck-5.3.4.exe C:\Developer\Tools\javascript\ext-4.2.1\src --builtin-classes --images C:\Developer\Tools\javascript\ext-4.2.1\docs\images --warnings=-no_doc,-dup_member,-link_ambiguous --external XMLHttpRequest --ignore-global --pretty-json --export=full --output ExtJS_4.2.1

Then point the generator at that directory containing those JSON files.

That said, every version of Ext JS and Touch has errors in the JSDuck docs or in the API that I have to add special case workarounds for. So I'm not sure how much luck you'll have trying to generate definitions yourself.
